spring.application.name=BlogApplication

#Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/blog_application
spring.datasource.username=postgres
spring.datasource.password=Ka@12345
spring.datasource.driver-class-name=org.postgresql.Driver


#JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Security Settings
spring.security.user.name=kapil
spring.security.user.password=Ka@12345


jwt.secret=kM+H9KfAqXo1Ij+f5E6y7P0Qb6KmWJhE3pX5a8a1zDo=
jwt.expiration=86400000 

